INSERT INTO database_name.table_name;
INSERT OR ROLLBACK INTO table_name;
INSERT OR ABORT INTO table_name;
INSERT OR REPLACE INTO table_name;
INSERT OR FAIL INTO table_name;
INSERT OR IGNORE INTO table_name SELECT *;
REPLACE INTO table_name DEFAULT VALUES;